<!doctype html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Error handling - try/catch block</title>
  <meta name="generator" content="CherryTree">
  <link rel="stylesheet" href="res/styles3.css" type="text/css" />
</head>
<body>
<div class='page'><strong><h1>#Error handling - try/catch block</h1></strong><br />You have to predict when code might fail.<br /><br />Put the code you predict might fail inside of a <code>try</code> block<br />And write the error handling process inside of a <code>catch</code> block<br />    You can have multiple <code>catch</code> blocks to handle multiple errors<br />    <br /><br /><strong><h2>Automatic exceptions</h2></strong><br />When a program executes in a <code>try</code> block, if an error occurs an exception object will get thrown automatically.<br /><br />As an argument in the <code>catch</code> statement, you can reference the exception that gets thrown.<br />    e.g. <code>catch(exception &amp;error)</code><br />    You specify that the argument is an exception type - <code>exception</code><br />    And assign it a name (a variable) prefixed by the <code>&amp;</code> reference operator - <code>&amp;error</code><br />    <br />Use <code>.what()</code> to retrieve the error<br /><br /><div class="codebox"><div class="codebox">#include&nbsp;&lt;iostream&gt;<br />#include&nbsp;&lt;string&gt;<br />using&nbsp;namespace&nbsp;std;<br /><br />int&nbsp;main()&nbsp;<span style="color:#000000;font-weight:400">{</span><br />string&nbsp;muhString&nbsp;=&nbsp;&quot;hey&quot;;<br />&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;muhString.erase(4,&nbsp;6);<br />&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;catch(exception&nbsp;&amp;error)&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cerr&nbsp;&lt;&lt;&nbsp;&quot;Exception:&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;error.what()&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br /><span style="color:#000000;font-weight:400">}</span></div></div><br /><br /><strong><h3>Automatic exceptions - catch specific errors/handle multiple errors</h3></strong><br />To catch specific errors, you can use the <code>&lt;stdexcept&gt;</code> library<br />The C++ library <code>&lt;stdexcept&gt;</code> defines a number of execpetion classes.<br /><br />exception                                                General exception<br />    bad_alloc                                                   - failure allocating storage<br />    bad_cast                                                    - failure casting data type<br />    bad_typeid                                                 - failure referencing typeid<br />    logic_error                                                  Logic exception<br />        domain_error                                                - invalid domain<br />        invalid_argument                                         - invalid argument call<br />        length_error                                                  - invalid length for container<br />        out_of_range                                                - invalid element range<br />    runtime_error                                               Runtime exception<br />        range_error                                                   - invalid range request<br />        overflow_error                                              - invalid arithmetic request        <br />        <br />You can specify any of the above in a <code>catch()</code> block instead of the normal exception type.<br />Combine specific exceptions along with a general exception as the last <code>catch</code> to handle all errors e.g. <br /><div class="codebox"><div class="codebox">#include&nbsp;&lt;iostream&gt;<br />#include&nbsp;&lt;string&gt;<br />#include&nbsp;&lt;fstream&gt;<br />#include&nbsp;&lt;stdexcept&gt;<br />using&nbsp;namespace&nbsp;std;<br /><br />int&nbsp;main()&nbsp;<span style="color:#000000;font-weight:400">{</span><br />&nbsp;&nbsp;&nbsp;&nbsp;string&nbsp;lang&nbsp;=&nbsp;&quot;hey&quot;;<br />&nbsp;&nbsp;&nbsp;&nbsp;try<br />&nbsp;&nbsp;&nbsp;&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lang.replace(100,&nbsp;1,&nbsp;&quot;h&quot;);<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;catch(out_of_range&amp;&nbsp;e)<br />&nbsp;&nbsp;&nbsp;&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cerr&nbsp;&lt;&lt;&nbsp;&quot;Range&nbsp;exception:&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;e.what()&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cerr&nbsp;&lt;&lt;&nbsp;&quot;Program&nbsp;terminated.&quot;&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;catch(exception&nbsp;&amp;e)<br />&nbsp;&nbsp;&nbsp;&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cerr&nbsp;&lt;&lt;&nbsp;&quot;Exception:&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;e.what()&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cerr&nbsp;&lt;&lt;&nbsp;&quot;Exception&nbsp;type:&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;typeid(e).name()&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cerr&nbsp;&lt;&lt;&nbsp;&quot;Program&nbsp;terminated.&quot;&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;cout&nbsp;&lt;&lt;&nbsp;&quot;Program&nbsp;continues...&quot;&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br /><span style="color:#000000;font-weight:400">}</span></div></div><br /><br /><br /><strong><h2>Identifying errors</h2></strong><br />When the <code>&lt;stdexcept&gt;</code> library is made available to the program, the exception classes can be used to identify the type of execution thrown.<br />Exception type information is provided by the <code>&lt;typeinfo&gt;</code> library<br /><code>&lt;typeinfo&gt;</code>&#39;s <code>typeid()</code> function accepts an exception argument, and its <code>name()</code> function returns the type name<br /><br />Use <code>.typeid(error).name()</code> to retrive the type of error<br /><br />#include &lt;iostream&gt;<br /><div class="codebox"><div class="codebox">#include&nbsp;&lt;string&gt;<br />#include&nbsp;&lt;fstream&gt;<br />#include&nbsp;&lt;stdexcept&gt;<br />#include&nbsp;&lt;typeinfo&gt;<br />using&nbsp;namespace&nbsp;std;<br /><br />int&nbsp;main()&nbsp;<span style="color:#000000;font-weight:400">{</span><br />&nbsp;&nbsp;&nbsp;&nbsp;string&nbsp;lang&nbsp;=&nbsp;&quot;hey&quot;;<br />&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;num&nbsp;=&nbsp;1000000000000;&nbsp;//&nbsp;1&nbsp;billion<br />&nbsp;&nbsp;&nbsp;&nbsp;try<br />&nbsp;&nbsp;&nbsp;&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lang.resize(8&nbsp;*&nbsp;num);<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;catch(exception&nbsp;&amp;e)<br />&nbsp;&nbsp;&nbsp;&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cerr&nbsp;&lt;&lt;&nbsp;&quot;Exception:&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;e.what()&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cerr&nbsp;&lt;&lt;&nbsp;&quot;Exception&nbsp;type:&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;typeid(e).name()&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cerr&nbsp;&lt;&lt;&nbsp;&quot;Program&nbsp;terminated.&quot;&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;cout&nbsp;&lt;&lt;&nbsp;&quot;Program&nbsp;continues...&quot;&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br /><span style="color:#000000;font-weight:400">}</span></div></div><br /><br /><br /><strong><h2>Manually throwing errors</h2></strong><br />You can manually <code>throw()</code> errors over to a catch block<br /><br /><div class="codebox"><div class="codebox">#include&nbsp;&lt;iostream&gt;<br />using&nbsp;namespace&nbsp;std;<br /><br />int&nbsp;main()&nbsp;<span style="color:#000000;font-weight:400">{</span><br />&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for(int&nbsp;number&nbsp;=&nbsp;1;&nbsp;number&nbsp;&lt;&nbsp;21;&nbsp;number++)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(number&nbsp;&gt;&nbsp;4)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw(number);<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;else&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cout&nbsp;&lt;&lt;&nbsp;&quot;Number:&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;number&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;catch(int&nbsp;num)&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cout&nbsp;&lt;&lt;&nbsp;&quot;Exception&nbsp;at:&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;num&nbsp;&lt;&lt;&nbsp;endl;<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br /><span style="color:#000000;font-weight:400">}</span></div></div><br /></div>
</body>
</html>
